
"""OOP-project-with-nlpcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJxhJb9wsVFJgnl9XL2Cp67UDo2LcdFj
"""

!pip install nlpcloud

import nlpcloud

class NLPApp:

  def __init__(self):
    self.__database = {}
    self.__first_menu()

  def __first_menu(self):
    user_input = input("""
    Hi! how would you like to proceed?
    1. Not a member? Register
    2. Already a member? login
    3. Exit
    """)
    if user_input == '1':
      self.__register()
    elif user_input == '2':
      self.__login()
    else :
      exit()

  def __register(self):
    name = input('enter you name ')
    email = input('enter you email ')
    password = input('enter you password ')

    if email in self.__database :
      print("Email is already registered !")
    else :
      self.__database[email] = [name , password]
      # print(self.__database)
      self.__login()

  def __login(self):
    email = input("enter you email ")
    password = input("enter you password ")

    if email in self.__database :
      if password == self.__database[email][1]:
        print('login successfully ')
        self.__second_menu()
      else :
        print('password is incorrect ')
        self.__login()
    else :
      print('email is not registered ')
      self.__first_menu()


  def __second_menu(self):
    user_input_2 = input("""
    Hi! how would you like to proceed?
    1. sentiment ananlysis
    2. Language Detection
    3. Grammar_and_Spelling_Correction
    4. Logout
    """)

    if user_input_2 == '1':
      self.__sentiment_analysis()
    elif user_input_2 == '2':
      self.__language_detection()
    elif user_input_2 == '3':
      self.__Grammar_and_Spelling_Correction()
    elif user_input_2 == '4':
      self.__first_menu()
    else:
      print("invalid input ")
      self.__second_menu()


  def __sentiment_analysis(self):
      pera = input("enter you paragraph ")

      client = nlpcloud.Client("finetuned-llama-3-70b", "60c66b87dd7a63d2874197733dbced8297f5bf37", gpu=True)
      response = client.sentiment(
          pera ,
          target="NLP Cloud"
      )

      L = []
      for i in response['scored_labels']:
        L.append(i['score'])

      index = sorted(list(enumerate(L)),key=lambda x:x[1],reverse=True)[0][0]

      print(response['scored_labels'][index]['label'])


  def __language_detection(self):
      pera = input("enter you paragraph ")

      client = nlpcloud.Client("python-langdetect", "fb039440058663761a780f52e3cd6e49fc45a58a", gpu=False)
      response = client.lang_detection(
          pera
      )

      print(response)

  def __Grammar_and_Spelling_Correction(self):
      pera = input("enter you paragraph ")

      client = nlpcloud.Client("finetuned-llama-3-70b", "fb039440058663761a780f52e3cd6e49fc45a58a", gpu=True)
      response = client.gs_correction(
          pera
      )
      print(response)

obj = NLPApp()

import nlpcloud

client = nlpcloud.Client("finetuned-llama-3-70b", "60c66b87dd7a63d2874197733dbced8297f5bf37", gpu=True)
client.sentiment(
    """I hate convoluted products with poor documentation. I see such products all the time. But NLP Cloud is not like that!""",
    target="NLP Cloud"
)